"""ChromaDB 매니저.

- housing / finance 두 컬렉션을 분리 관리한다.
- 메타데이터 포함 임베딩 저장 / 검색 / 통계 조회 기능 제공.
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Iterable, List, Optional

from langchain_core.embeddings import Embeddings
from langchain_core.documents import Document
from langchain_chroma import Chroma
import chromadb
from langchain_openai import OpenAIEmbeddings
from dotenv import load_dotenv

# ROOT 경로 설정 및 .env 로드
DATA_DIR = Path(__file__).resolve().parent.parent / "data"
ROOT_DIR = DATA_DIR.parent
load_dotenv(ROOT_DIR / ".env")

# 주택·금융 DB는 별도 디렉토리에 분리 저장
HOUSING_DB_DIR = DATA_DIR / "db" / "chroma_db_v2"
FINANCE_DB_DIR  = DATA_DIR / "db" / "chroma_finance"
HOUSING_DB_DIR.mkdir(parents=True, exist_ok=True)
FINANCE_DB_DIR.mkdir(parents=True, exist_ok=True)

HOUSING_COLLECTION = "youth_housing_policy"
FINANCE_COLLECTION = "youth_finance_policy"
DEFAULT_EMBED_MODEL = "text-embedding-3-small"

# Collapsed Tree RAPTOR DB generated by the sibling housing-policy project.
RAPTOR_DB_DIR = Path(os.getenv(
    "RAPTOR_CHROMA_DIR",
    "/Users/sblim/2026_HK_LLM_MID_PJT/new_project/youth_housing_policy/data/chroma",
))
RAPTOR_COLLECTION = os.getenv("RAPTOR_CHROMA_COLLECTION", "youth_housing")
RAPTOR_EMBED_MODEL = os.getenv("RAPTOR_EMBED_MODEL", "BAAI/bge-m3")


def get_embeddings(model: Optional[str] = None) -> OpenAIEmbeddings:
    api_key = os.getenv("OPENAI_API_KEY")
    return OpenAIEmbeddings(model=model or DEFAULT_EMBED_MODEL, api_key=api_key)


class SentenceTransformerEmbeddings(Embeddings):
    """LangChain embedding adapter for the existing bge-m3 RAPTOR Chroma DB."""

    def __init__(self, model_name: str = RAPTOR_EMBED_MODEL):
        from sentence_transformers import SentenceTransformer

        self.model_name = model_name
        self.model = SentenceTransformer(model_name, device="cpu")

    def embed_documents(self, texts: List[str]) -> List[List[float]]:
        vecs = self.model.encode(texts, normalize_embeddings=True, show_progress_bar=False)
        return vecs.tolist()

    def embed_query(self, text: str) -> List[float]:
        return self.embed_documents([text])[0]


def _db_dir(collection: str) -> Path:
    """컬렉션 이름으로 해당 DB 디렉토리를 반환."""
    if collection == FINANCE_COLLECTION:
        return FINANCE_DB_DIR
    return HOUSING_DB_DIR


def get_vectorstore(collection: str, embeddings: Optional[OpenAIEmbeddings] = None) -> Chroma:
    from chromadb.config import Settings
    embeddings = embeddings or get_embeddings()
    client = chromadb.PersistentClient(
        path=str(_db_dir(collection)),
        settings=Settings(anonymized_telemetry=False),
        tenant="default_tenant",
        database="default_database",
    )
    return Chroma(
        client=client,
        collection_name=collection,
        embedding_function=embeddings,
    )


def get_raptor_vectorstore() -> Chroma:
    """Return the existing collapsed-tree RAPTOR Chroma collection.

    This collection was embedded with BAAI/bge-m3 (1024 dimensions), so it must
    not share the OpenAI embedding function used by the default housing DB.
    """
    from chromadb.config import Settings

    embeddings = SentenceTransformerEmbeddings(RAPTOR_EMBED_MODEL)
    client = chromadb.PersistentClient(
        path=str(RAPTOR_DB_DIR),
        settings=Settings(anonymized_telemetry=False),
        tenant="default_tenant",
        database="default_database",
    )
    return Chroma(
        client=client,
        collection_name=RAPTOR_COLLECTION,
        embedding_function=embeddings,
    )


try:
    import streamlit as st

    @st.cache_resource(show_spinner=False)
    def get_cached_vectorstore(collection: str) -> Chroma:
        """앱 시작 시 한 번만 로드하고 세션 간 재사용."""
        return get_vectorstore(collection)

    @st.cache_resource(show_spinner=False)
    def get_cached_raptor_vectorstore() -> Chroma:
        """Collapsed Tree RAPTOR DB 로드."""
        return get_raptor_vectorstore()

except ImportError:
    def get_cached_vectorstore(collection: str) -> Chroma:
        return get_vectorstore(collection)

    def get_cached_raptor_vectorstore() -> Chroma:
        return get_raptor_vectorstore()


def add_documents(collection: str, docs: Iterable[Document]) -> int:
    docs = list(docs)
    if not docs:
        return 0
    vs = get_vectorstore(collection)
    vs.add_documents(docs)
    return len(docs)


def reset_collection(collection: str) -> None:
    """컬렉션을 완전히 비웁니다."""
    try:
        vs = get_vectorstore(collection)
        # 1. 모든 ID를 가져와서 삭제 (가장 확실한 방법)
        existing = vs._collection.get()
        if existing and existing['ids']:
            vs._collection.delete(ids=existing['ids'])
        
        # 2. 컬렉션 자체 삭제 시도 (필요한 경우)
        vs.delete_collection()
    except Exception as e:
        print(f"Error resetting collection {collection}: {e}")


def count_documents(collection: str) -> int:
    try:
        vs = get_vectorstore(collection)
        return vs._collection.count()
    except Exception as e:
        # 에러 원인을 파악하기 위해 무조건 출력합니다.
        print(f"!!! DB 조회 에러 ({collection}): {e}")
        return 0


def get_all_sources(collection: str) -> List[str]:
    """컬렉션에 저장된 문서들의 유니크한 source(파일명) 목록을 반환합니다."""
    try:
        vs = get_vectorstore(collection)
        # 대량의 데이터일 경우를 대비해 metadata만 가져옵니다.
        result = vs._collection.get(include=["metadatas"])
        metadatas = result.get("metadatas", [])
        
        sources = set()
        for meta in metadatas:
            if meta and "source" in meta:
                sources.add(meta["source"])
        
        return sorted(list(sources))
    except Exception as e:
        print(f"Error getting sources for {collection}: {e}")
        return []


def similarity_search(
    collection: str,
    query: str,
    k: int = 2,
) -> List[Document]:
    vs = get_vectorstore(collection)
    return vs.similarity_search(query, k=k)


def collections_status() -> dict:
    return {
        "housing": count_documents(HOUSING_COLLECTION),
        "finance": count_documents(FINANCE_COLLECTION),
    }
